export const genres: Record<number, string> = {
  1: 'Action',
  2: 'Adventure',
  3: 'Cars',
  4: 'Comedy',
  5: 'Avgante Garde',
  6: 'Demons',
  7: 'Mystery',
  8: 'Drama',
  9: 'Ecchi',
  10: 'Fantasy',
  11: 'Game',
  12: 'Hentai',
  13: 'Historical',
  14: 'Horror',
  15: 'Kids',
  17: 'Martial Arts',
  18: 'Mecha',
  19: 'Music',
  20: 'Parody',
  21: 'Samurai',
  22: 'Romance',
  23: 'School',
  24: 'Sci-Fi',
  25: 'Shoujo',
  26: 'Girls Love',
  27: 'Shounen',
  28: 'Boys Love',
  29: 'Space',
  30: 'Sports',
  31: 'Super Power',
  32: 'Vampire',
  35: 'Harem',
  36: 'Slice of Life',
  37: 'Supernatural',
  38: 'Military',
  39: 'Police',
  40: 'Psychological',
  41: 'Seinen',
  42: 'Josei',
  43: 'Doujinshi',
  44: 'Gender Bender',
  45: 'Suspense',
  46: 'Award Winning',
  47: 'Gourmet',
  48: 'Work Life',
  49: 'Erotica',
};

export const getGenreName = (id: number) => genres[id] || 'Unknown';
